stages:
  preprocess:
    cmd: python src/stages/preprocessing.py --config=params.yaml
    deps:
    - src/stages/preprocessing.py
    params:
    - base
    - data.data_load
    outs:
    - ${data.data_preprocessing}
  
  featurize:
    cmd: python src/stages/featurizing.py --config=params.yaml
    deps:
    - data/processed/processed_data.csv
    - src/stages/featurizing.py
    params:
    - data.data_preprocessing
    - featurize
    outs:
    - ${data.data_featurized}
    - ${featurize.featurizer_path}
  
  train:
    cmd: python src/stages/training.py --config=params.yaml
    deps:
    - ${data.data_featurized}
    - src/stages/training.py
    - src/utils/train_util.py
    params:
    - base
    - train
    outs:
    - ${train.model_path}
    - ${data.data_labeled}
    metrics:
    - reports/metrics.json:
        cache: false
    plots:
    - reports/figures/clusters.png:
        cache: false