stages:
  preprocess:
    cmd: python src/stages/preprocessing.py --config=params.yaml
    deps:
    - src/stages/preprocessing.py
    params:
    - base.log_level
    - data.data_load
    outs:
    - ${data.data_preprocessing}
  
  featurize:
    cmd: python src/stages/featurizing.py --config=params.yaml
    deps:
    - ${data.data_preprocessing}
    - src/stages/featurizing.py
    params:
    - base
    - data.data_preprocessing
    - featurize
    outs:
    - ${data.data_featurized}
    - ${featurize.featurizer_path}
  
  train:
    cmd: python src/stages/training.py --config=params.yaml
    deps:
    - ${data.data_featurized}
    - src/stages/training.py
    - src/utils/train_util.py
    params:
    - base
    - train
    outs:
    - ${train.model_path}
    - ${data.data_labeled}
    metrics:
    - reports/metrics.json:
        cache: false
  
  visualize:
    cmd: python src/stages/visualization.py --config=params.yaml
    deps:
    - ${data.data_preprocessing}
    - ${data.data_labeled}
    - src/stages/visualization.py
    params:
    - reports
    frozen: true
    plots:
    - ${reports.base_dir}/${reports.plots_dir}/${reports.plots.clusters}:
        cache: false
    - ${reports.base_dir}/${reports.plots_dir}/${reports.plots.comparison}:
        cache: false
    - ${reports.base_dir}/${reports.plots_dir}/${reports.plots.frequency}:
        cache: false
