base:
  random_state: 42
  log_level: INFO
data:
  data_load: data/raw/Customer_Data.csv
  data_preprocessing: data/processed/processed_data.csv
  data_featurized: data/processed/featurized_data.csv
  data_labeled: data/processed/labeled_data.csv
reports:
  base_dir: reports
  plots_dir: figures
  metrics_file: metrics.json
  plots:
    silhouette: silhouette_plot.png
    elbow: elbow_plot.png
    clusters: clusters.png
    comparison: comparison.png
    frequency: frequency.png
train:
  model_path: models/model.pkl
  model:
    model_name: kmeans
    param_grid:
      n_clusters:
      - 2
      - 3
      - 4
      - 5
      - 6
      n_init:
      - 10
featurize:
  featurizer_name: autoencoder
  featurizer_path: models/featurizer.keras
  model_name: model1
  model_path: models/autoencoder/
  parameters:
    encoding_dim: 6
  hyperparameters:
    encoder_activation: tanh
    decoder_activation: tanh
    optimizer: adam
    loss: binary_crossentropy
    epochs: 15
    batch_size: 64
visualization:
  n_components: 2
  perplexity: 50
  learning_rate: 500
  n_iter: 3000
