base:
  random_state: 42
  log_level: INFO

data:
  data_load: data/raw/Customer_Data.csv
  data_preprocessing: data/processed/processed_data.csv
  data_featurized: data/processed/featurized_data.csv
  data_labeled: data/processed/labeled_data.csv

reports:
  base_dir: reports
  plots_dir: figures
  metrics_file: metrics.json
  plots:
    silhouette: silhouette_plot.png
    elbow: elbow_plot.png
    clusters: clusters.png
