base:
  random_state: 42
  log_level: INFO

data_load:
  dataset_csv: data/raw/Customer_Data.csv

data_preprocessing:
  dataset_processed: data/processed/processed_data.csv

reports:
  base_dir: reports
  plots_dir: figures
  metrics_file: metrics.json
  plots:
    silhouette: silhouette_plot.png
    elbow: elbow_plot.png
